HabanaAI/vllm-hpu-extension

vllm_hpu_extension/ops.py, vllm_hpu_extension/punica_hpu.py
This ports LoRA-specific changes to vllm.hpu introduced in https://github.com/HabanaAI/vllm-fork/pull/290 to extension path.
=> Add LoRA extensions

vllm_hpu_extension/rotary_embed.py
Since LLama3.1 additional rope scaling was added which was not handled by our RotaryEmbedding implementation. Due to that FusedRoPE was not used.
This PR adds `HpuLlama3RotaryEmbedding` based on the [Llama3RotaryEmbedding](https://github.com/HabanaAI/vllm-fork/blob/habana_main/vllm/model_executor/layers/rotary_embedding.py#L673) which allows to use scaling and FusedRoPE together.
=> Add rope_scaling support for LLama3.1

vllm_hpu_extension/ops.py
This introduces another algorithm for softmax normalization - wsum (weighted sum).
The main idea is that we can normalize softmax values by a weighted sum of the local block maximums, i.e. a = sum(w * max(attn)). In most cases the weights (or block_scales) are selected so be equal to 1/num_blocks so that the sum doesn't explode with a larger number of blocks.
=> Softmax: add weighted-sum normalization

vllm_hpu_extension/cache_ops.py, vllm_hpu_extension/ops.py, vllm_hpu_extension/rotary_embed.py
migrating some parts of [PR in vllm-fork](https://github.com/HabanaAI/vllm-fork/pull/162)
changes:
* changes on rope forward to work well(fast) with context
* updated deprecated cache ops to work (block mapping has changed from dict to tensor)
* added prompt_attention_with_context for prefill with context(cached prefix)
will update the main PR in vllm-fork too.
=> add: migrate changes for prefix caching from vllm repository

vllm_hpu_extension/ops.py
Adds support for selecting softmax normalization algorithm (via VLLM_PA_SOFTMAX_IMPL):
'wsum'
'amax'
'head_amax'
'wsum_head_amax'
'index_reduce'
'scatter_reduce'
'wsum_head_amax' is selected by default as it should help with Qwen2 accuracy issues.
=> Add support for various softmax normalization options

vllm_hpu_extension/utils.py
Contiguous fetch from cache to avoid using costly gather operations. Requires changes made to hpu_model_runner in vllm-fork to work. Introduces redundant calculations in decoding phase. In all tested cases improves performance over the entire run. For even better performance cache defragmentation is required.
=> Contiguous PA

vllm_hpu_extension/capabilities.py, vllm_hpu_extension/environment.py, vllm_hpu_extension/ops.py, vllm_hpu_extension/test_capabilities.py
This allows specifying which capabilities are available in current build. For example this can be used to enable certain algorithms when we know that current build supports them.
=> Implement capability checking

vllm_hpu_extension/capabilities.py, vllm_hpu_extension/environment.py, vllm_hpu_extension/ops.py, vllm_hpu_extension/test_capabilities.py
There are some issues with enabling index_reduce by default. We need to sort them out first without blocking changes to vllm-hpu-extension
=> Allow specifying negative compatibilities + disable index_reduce

vllm_hpu_extension/ops.py
Reverts HabanaAI/vllm-hpu-extension#26
It causes perf regressions + the problem is not reproducible on recent builds
=> Revert "do not use softmax fast mode in FusedSDPA"

vllm_hpu_extension/ops.py
I am trying APC on Gaudi and met error as below. Propose this fixing here
```
[rank0]:   File "/home/chendixue/vllm/vllm/model_executor/models/llama.py", line 192, in forward
[rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
[rank0]:   File "/home/chendixue/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1556, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/chendixue/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1606, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/home/chendixue/vllm/vllm/attention/layer.py", line 99, in forward
[rank0]:     return self.impl.forward(query,
[rank0]:   File …
```
=> [BUGFIX]Fix attn_bias as None for Auto Prefix caching

vllm_hpu_extension/ops.py
As FusedSdpa handles repeat cache in it's implementation since Synapse 1.18, remove python level work-around
=> Remove uncessary repeat cache when FusedSdpa is used.

vllm_hpu_extension/ops.py
It may be possible that on older builds index_reduce op is not supported. In that case add option to automatically fallback  index_reduce to wsum_head_amax.
=> Backward compatibility of default normalization option

vllm_hpu_extension/ops.py
This PR implements Pipelined PagedAttention, that applies the concepts of FlashAttention into PagedAttention.
The concept is to perform matmul_av (A @ V), before calculating grouped maximum (max value shared between blocks for single sequence) and grouped sum (sum of exponents that belongs to the same sequence).
Thanks to that, we can perform softmax calculation in parallel to A @ V calculation. 
In the end, just like in FlashAttention we need to apply softmax rescaling to correct denominator. 
This PR also clean-ups the code so we have only one way of performing normalization for exponent.
=> Pipeline PagedAttention

vllm_hpu_extension/ops.py
Previous solution caused a bug in models that have specific layout of [num_blocks, 1, num_heads , ...], which occurs in granite-20b.
=> Fix adjustment tensor shape in PipelinedPA so that it matches with any possible layout

vllm_hpu_extension/profiler.py
This change enables new mode ```VLLM_PROFILER_ENABLED=full``` which contains events from PyTorch profiler and high-level profiler in one trace.
=> [SW-206682] Add host traces to high-level profilings

vllm_hpu_extension/profiler.py
get_vllm_instance_id was removed in https://github.com/vllm-project/vllm/pull/10976. This PR removes the dependency on that function.
=> Remove get_vllm_instance_id dependency

vllm_hpu_extension/ops.py, vllm_hpu_extension/punica_hpu.py
This PR updates LoRA function names to align with latest vllm.lora.punica. https://github.com/vllm-project/vllm/pull/10917
=> Align function names with Punica

vllm_hpu_extension/ops.py
**Required for associated changes on [vllm-fork PR](https://github.com/HabanaAI/vllm-fork/pull/503)**
See the associated ticket above for further details.
=> Resolved ALIBI bias regression due to porting flat PA

vllm_hpu_extension/bucketing.py
Allows env flag `VLLM_MAX_BATCHED_PROMPT_LEN` to cutoff prompt lengths for which to generate batched bucket.
E.g if `VLLM_MAX_BATCHED_PROMPT_LEN=1024`, any bucket with `seqlen > 1024` and `bs > 1` will be removed from the warmup buckets.
=> Generate batched prompt buckets for 'short' sequences

vllm_hpu_extension/capabilities.py, vllm_hpu_extension/ops.py
index_reduce is available in latest released version. No need to have a separate pa implementation as pipelined pa outperforms previous implementation.
=> Removed previous (not-pipelined) pa implementation

vllm_hpu_extension/ops.py
When run with VLLM_FP32_SOFTMAX=true both prompt attention (if FSDPA is disabled) and flat_pa will keep mme accumulated values from Q@K in fp32 and run softmax normalization in fp32 which helps with numerical errors in certain models like Qwen2.
This code should have no effect if the feature is disabled.
=> Add flag to enable running softmax in fp32

vllm_hpu_extension/gptq_hpu.py
Based on https://github.com/HabanaAI/vllm-fork/pull/481, I added gptq hpu class for enabling GPTQ quantized models.
=> Add GPTQ class

vllm_hpu_extension/awq_hpu.py
Based on https://github.com/HabanaAI/vllm-fork/pull/458, I added awq hpu class for enabling AWQ quantized models.
=> Add AWQ class

calibration/step-5-unify_measurements.py
Add error handing, or it will give the wrong debug info and open a None file at the following.
=> Add error handing in unify measurements.

vllm_hpu_extension/environment.py
This fixes running cpu-tests as habana-torch-plugin is not available there
=> Return dummy value as build for fake-hpu

vllm_hpu_extension/profiler.py
Small bug was introduced in https://github.com/HabanaAI/vllm-hpu-extension/pull/52/files 
line 69:
if `vllm_instance_id` is None then `self.filename = server_events_None.json`
Kudos to @tianmu-li !
=> Fix high-level profiler filename

vllm_hpu_extension/flags.py
Using VLLM_PROMPT_USE_FUSEDSDPA = 1 with mllama causes acc regression, so we need to set it to 0 by default
=> Set default VLLM_PROMPT_USE_FUSEDSDPA = 0 for mllama

vllm_hpu_extension/bucketing.py
The PR fixes an issue with extra block size padding being added to some buckets, because of incorrect  searching for the closest power of 2 value.
INFO 02-14 10:20:30 hpu_model_runner.py:1740] [Warmup][Decode][5/20] batch_size:8 num_blocks:**256** free_mem:30.88 GiB
Bucket after padding: (8, **512**, False)
INFO 02-14 10:20:30 hpu_model_runner.py:1740] [Warmup][Decode][6/20] batch_size:16 num_blocks:**128** free_mem:30.88 GiB
Bucket after padding: (16, **512**, False)
=> Power of 2 padding fix

calibration/step-1-prepare-calibration-dataset.py
For models without vocab.json, the tokenizer initialization will failed with stack as below when use_fast as True.
Add a retry to get auto tokenizer with use_fast as False. So it can use tokenizer_config.json to initialize tokenizer. 
File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt2/tokenization_gpt2.py", line 153, in __init__
with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
Error in step 1
=> Fix ibm granite model calibration issue.

vllm_hpu_extension/flags.py, vllm_hpu_extension/ops.py
Changes:
- Added back alibi biases to decode stage.
- Optimized ALiBI memory usage.
- Added environment variable "VLLM_PROMPT_ALIBI_MAX_SEQ_LEN" to allow large models to run with restricted prompt lengths.
- Prompt biases instantiated once in __init__ rather than each forward.
- Prompt and decode biases are shared across encoder/decoder layers.
- Added environment variable "VLLM_ALIBI_USE_FLOAT32_BIASES" to resolve accuracy issue on long sequences.
- Updated jais, mpt, falcon, baichuan, and bloom to work with ALiBI.
- Due to bloom's 176B parameter size I was unable to test this model. Its changes are the simplest though.
- Works in lazy and eager mode.
- ALiBI is restricted to "VLLM_PROMPT_USE_FUSEDSDPA=false", and "VLLM_CONTIGUOUS_PA=true".
- Add position offsets to improve quality on BS …
=> vLLM-Ext: Full enabling of ALiBi

vllm_hpu_extension/ops.py
Fix hard code of experts max number for moe kernel，
Verifed by qwen2-moe and deepseek-v2-lite
=> Fix hard code of experts max number for moe kernel

vllm_hpu_extension/ops.py
- Set default softmax mode to bf16 to improve accuracy. Negligible impact on the performance is observed in the profile.
- Add fp32 softmax option and fix the accuracy issue by setting `valid_seq_lengths = None` for FusedSDPA since v1.20.0
=> set default softmax mode to bf16 and add fp32 option for FusedSDPA

vllm_hpu_extension/ops.py, vllm_hpu_extension/scales.py
https://jira.habana-labs.com/browse/SW-207506
=> add ScaleToHwAligned for fp8 vllm model loading

vllm_hpu_extension/ops.py
This commit is to update vllm-hpu-extension for Deepseek_r1 integration:
1. add a new page_attention method - flat_pa_mla
* support to split value from Key
* move transpose after splitting, which works better for GC
2. Add expert parallel support for VllmMixtureOfExpertsOp, and enable a quick fix for segment fault in 1.20 when num_experts exceed 64
3.  add VllmMixtureOfExpertsOpFP8 and MoeFP8Matmul for running out-of-box block-wise fp8 models.
* enabled expert parallel 
* aligned with INC with API, so it can be converted to patchedVllmMixtureOfExpertsOpFP8 and patchedMoeFP8Matmul for static quant and dynamic quant path
4. added necessary functions for block-wise fp8 handling:
* pad_weight # works for block-wise fp8 when weight is not block_size aligned
* unpad_weight  # works for …
=> [DeepseekR1] 1.21 release support necessary changes

calibration/README.md, calibration/calibrate_model.sh, calibration/step-2-measure-scales.py, calibration/step-3-postprocess_measure.py, calibration/step-4-quantize-scales.py
Added:
- `-c` parameter to enable passing trust remote code to vllm
- quant config for deepseek
- block quant support for step 2 and step 4 (changing quant type to fp8)
- needed variables for deepseek measurements
Script with changes was validated for Deepseek-R1 and Mixtral 8x7B
=> Add support of deepseek fp8 calibration

vllm_hpu_extension/bucketing/exponential.py
fix for contigious pa number of decodes blocks
=> Fix for contigious pa number of decodes blocks for exponential bucketing

vllm_hpu_extension/ops.py
This PR is to port #137 to main, so we can leverage that to work on habana_main for deepseek_r1 enabling
=> [DeepseekR1] porting 1.21 deepseek changes to main (#137)

vllm_hpu_extension/flags.py, vllm_hpu_extension/kernels.py, vllm_hpu_extension/ops.py
This change introduces block_softmax_adjustment kernel, that is available since 1.22 release. The goal of this kernel is to fuse operations that were running on 2 different engines TPC & MME, and thanks to that improve overall performance of paged attention with faster execution and better pipelining.
All of the models running through the paged attention should benefit from this change. From my experiments the overall throughput gain ranges between 0.5% to 13%. Paged Attention itself is improved by 0.5% to 17%.
=> Introduce block_softmax_adjustment kernel

calibration/calibrate_model.sh
Previous:
vllm (pretrained=/models/Qwen2-7B-Instruct,dtype=bfloat16,quantization=inc,kv_cache_dtype=fp8_inc), gen_kwargs: (None), limit: None, num_fewshot: None, batch_size: 32
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.0281|±  |0.0045|
|     |       |strict-match    |     5|exact_match|↑  |0.0099|±  |0.0027|
After:
G2:
G3:
=> Recover Qwen2-7B-Instruct fp8 accuracy

vllm_hpu_extension/cache_ops.py, vllm_hpu_extension/ops.py, vllm_hpu_extension/utils.py
Change the layout of KV cache to (num_blocks * block_size, num_kv_heads, head_size). This will improve the performance as update will be done on 1D indices which will remove unnecessary transpose and memcopies due to low FCD.
Corresponding change: https://github.com/HabanaAI/vllm-fork/pull/1106
=> Flat KV cache layout

vllm_hpu_extension/ops.py
when I load [RedHatAI/Meta-Llama-3-8B-Instruct-FP8](https://huggingface.co/RedHatAI/Meta-Llama-3-8B-Instruct-FP8) to do inference on G3, the error raised. the root cause is vllm-fork rewrite the w8a8_utils.py(https://github.com/HabanaAI/vllm-fork/blob/habana_main/vllm/model_executor/layers/quantization/utils/w8a8_utils.py#L372) apply function with num_token_padding, but the name is different in vllm-hpu-extension. @Yantom1 @nirda7 @afierka-intel  @michalkuligowski 
when the PR merged, I also need improve the vllm-hpu-extension commit id in vllm-fork requirements-hpu.txt
cc: @thuang6 @linoybu 
reproduce steps:
envs:
vllm-fork: habana_main([c86b560](https://github.com/HabanaAI/vllm-fork/commit/c86b560da424dc3bcf7889e770bf74d5cad8f87b))
```python
from vllm import LLM
llm = …
```
=> fix scaled_fp8_quant parameter name to load RedHatAI fp8 model

vllm_hpu_extension/bucketing/linear.py
In linear bucketing there are cases when we create buckets with BS higher than num_blocks, which is not possible in real scenario - each sequence in a batch needs to have at least one block.
=> Skip dummy decode bucket when bs > num_blocks

calibration/vlm-calibration/README.md, calibration/vlm-calibration/calibrate_model.sh, calibration/vlm-calibration/requirements.txt
This is a follow-up PR for vlm calibration, see previous PR #172 and #174 
In this PR, we enable several optimization:
- support both local dataset and remote dataset from HuggingFace
- add some validation check on dataset path
- update readme on dataset
- pip install necessary packages
=> [vlm calibration] support download HF dataset & dataset robustness

vllm_hpu_extension/bucketing/exponential.py
Fix for contiguous pa number of decodes blocks for exponential bucketing #162
=> Fix for contiguous pa number of decodes blocks for exponential bucketing #162

vllm_hpu_extension/ops.py, vllm_hpu_extension/utils.py
Currently, we will leverage INC to support fp8 kv cache
Meaning, we need to specify quant_config and kv_cache_dtype = fp8_inc.
This PR would like to also walk around INC for native fp8 KV Cache support. Same method is adopted in TGI as well.
1. add FP8VLLMKVCACHE
2. add FP8MATMUL
How to run
No need to add quant_config in env var. need to use kv_cache_dtype
```
--kv_cache_dtype=fp8_inc
```
```
PT_HPU_LAZY_MODE=1 \
VLLM_SKIP_WARMUP=true \
PT_HPU_ENABLE_LAZY_COLLECTIVES=true \
PT_HPU_WEIGHT_SHARING=0 \
lm_eval --model vllm \
--model_args "pretrained=${MODEL_PATH},tensor_parallel_size=${TP_SIZE},distributed_executor_backend=mp,trust_remote_code=true,max_model_len=4096,use_v2_block_manager=True,dtype=bfloat16,enable_expert_parallel=True,max_num_seqs=128,kv_cache_dtype=fp8_inc" \
--tasks gsm8k …
```
=> SW-229036] add fp8_kvcache support

calibration/calibrate_model.sh
Fixes conditional statement where MULTI_NODE_SETUP should be used for distinguishing Single and Multi Node configuration.
=> Replace MULTI_NODE_RUN with MULTI_NODE_SETUP

calibration/calibrate_model.sh
deepseek-ai/DeepSeek-R1-Distill-Qwen-7B is a qwen2 model. It cannot use default calibration config. 
Fix https://habana.atlassian.net/browse/CS-1343
=> [aice/v1.20.1] Fix deepseek distill qwen2 7b fp8 calbiration

calibration/calibrate_model.sh
Qwen3 models use bfloat16 attention, set `scale_format="const"` to reduce the warmup duration. And keep `scale_format="scalar"` for other models to retain the GC optimization opportunities.
=> set scale_format to "const" for Qwen3 models and "scalar" otherwise

calibration/calibrate_model.sh
The graphs could be shared among the decode layers by setting `scale_format="const"` and `VLLM_DISABLE_MARK_SCALES_AS_CONST=true`, and the number of graphs to compile could be reduced significantly, which means faster warmup, while the runtime performance is worse than `scale_format="scalar"`.
=> keep scale_format="scalar" for qwen3 models for better runtime performance

vllm_hpu_extension/flags.py
This aligns with the default setting in latest habana_main.
=> enable fsdpa for qwen2 by default

calibration/calibrate_model.sh
Fixes conditional statement where MULTI_NODE_SETUP should be used for distinguishing Single and Multi Node configuration (1.21.2).
=> Replace MULTI_NODE_RUN with MULTI_NODE_SETUP (1.21.2)

vllm_hpu_extension/environment.py
vllm-hpu-extension is being used by other project for now and we want to avoid vllm installation. Thus, updating the snippet in this file to guard the vllm import.
=> Add guard for vllm import for getting engine version

calibration/calibrate_model.sh
This PR adds scale_format=CONST parameter to quant config for Mixtral with TC. It reduces graph breaks and improves accuracy.
=> Use different quant config for Mixtral TC and lazy

calibration/step-2-measure-scales.py
Cherry-pick of: https://github.com/HabanaAI/vllm-hpu-extension/commit/83d92fec3ad2de68280faadf569b0f8cee7ca100 to v1.22.0 branch
=> Port to v1.22.0: fix args order (#264)

vllm_hpu_extension/ops.py, vllm_hpu_extension/utils.py
This is to use custom FusedSDPA kernel with sliding_window for Gemma3. 
This kernel is used for text input(causal + window_size) , and text+image input(attn_mask + window_size).  
Below environment variables need to be set to this feature to work. 
SLICE_SIZE=1024 (this can be changed to multiple of block size) 
PT_HPU_SDPA_BR_FACTOR=SLICE_SIZE
PT_HPU_QKV_SLICE_SEQ_LEN_THLD=SLICE_SIZE
PT_HPU_SDPA_QKV_SLICE_MODE_FWD=1
=> Add support for FusedSDPA with window_size for Gemma3

vllm_hpu_extension/bucketing/exponential.py
Fixes (1, np.int64(640), 2) -> (1, 640, 2)
=> Cast buckets to int, fixes logs

vllm_hpu_extension/ops.py, vllm_hpu_extension/utils.py
window_size parameter was added for ModuleFusedSDPA,  however PatchedModuleFusedSDPA doesn't support this parameter. It seems this "fsdpa_op" in ops.py _fsdpa_prompt_attention can be any including these two and maybe others.  Passing this parameter only when we have valid info. 
Error seen without this patch.:
=========
FAILED test_lm_eval_correctness.py::test_lm_eval_correctness - TypeError: PatchedModuleFusedSDPA.forward_quant() takes from 4 to 12 positional arguments but 13 were given
=> Fix error for PatchedModuleFusedSDPA

vllm_hpu_extension/bucketing/exponential.py, vllm_hpu_extension/bucketing/linear.py
As title states. Does not change return values since we are sorting them into lists afterwards.
Some long context models hangs due to $O(n^2)$ over a hundreds of thousands of elements.
=> Use sets for faster filter checks. Better long context support

vllm_hpu_extension/bucketing/exponential.py
This PR is a fix to correct the `long_context` argument passed to `warmup_range_with_limit`.
The argument was hardcoded to `True`, ignoring the actual value determined by `bmax`. Now it correctly uses the` long_context` variable based on the `bmax` threshold.
=> Fix: Pass correct long_context flag to warmup_range_with_limit

vllm_hpu_extension/bucketing/common.py, vllm_hpu_extension/features.py
Customer requested us to use different BUCKET size for shorter length and longer length. 
We are doing this. 
- If seq_len is smaller than SLICE_THLD, then use FusedSDPA, and it will use BUCKET_STEP size.
- If seq_len is grater than SLICE_THLD, then use FusedSDPA with slice kernel, and it will use SLICE_SIZE(1024 default).
=> Choose different bucket when SLICE FusedSDPA is in use

vllm_hpu_extension/ops.py
This PR fixes the scaling issue for models like **Hunyuan**:
- `w2_scale_fp8` is provided as a scalar, but should be expanded to match the per-channel size.
- `w13_scale_fp8` is given in a combined form (two values for W1/W3) and needs to be reshaped and repeated to the correct size for per-channel quantization.
- Ensures that `w2_input_scale` is stored as a list (one per expert) instead of a single tensor.
=> Modify ops.py for hunyuan fp8 model implementation

vllm_hpu_extension/bucketing/common.py
generate_fallback_bucket should not be larger than max model length. Can potentially cause wamrup errors for some configurations.
@czhu15
=> Fix PP warmup issue when max model length is low

calibration/step-3-postprocess-measure.py
Due to the seperation of prefill and decoding modes, the output of fsdpa may differ with the input of o_proj, we need to fix that otherwise the accuracy may drop.
=> unify fsdpa output with o_proj input
