vllm_hpu_extension/profiler.py, vllm_hpu_extension/utils.py
This PR moves all the Habana-specific profilers to the extension.
=> Move Habana profilers to extension

vllm_hpu_extension/ops.py
index_reduce was implemented only with a subset of features. Those changes ensure that we're calling the right kernel.
=> Fix index_reduce to avoid CPU-fallbacks

vllm_hpu_extension/capabilities.py, vllm_hpu_extension/environment.py
Both getting current build and hw can fail when run in github actions. This PR adds detecting fake_hpu + allows handling missing data in Checks.
=> Fix capability detection on fake-hpu

vllm_hpu_extension/ops.py
To fix part of the issue of https://github.com/HabanaAI/vllm-fork/issues/443
=> do not use softmax fast mode in FusedSDPA

vllm_hpu_extension/ops.py
Only for the batch2block before the qk_matmul and the block2batch after the av_matmul.
=> Enable patching matmuls in block2batch and batch2block

vllm_hpu_extension/ops.py
Using in-place exp_(), which for some reason (to be investigated) blocked fusing sub+exp+sum in index_reduce normalization.
With that, the index_reduce is now faster than default normalization by ~1.3% for Llama3.1 bs=128 1k/1k bf16, num requests=256:
Default:
```
Throughput: 5.12 requests/s, 10483.28 total tokens/s, 5241.64 output tokens/s
```
index_reduce
```
Throughput: 4.95 requests/s, 10138.19 total tokens/s, 5069.09 output tokens/s
```
index_reduce + torch.exp() instead of exp_()
```
Throughput: 5.18 requests/s, 10615.93 total tokens/s, 5307.96 output tokens/s
```
i.e.: ~1.3% perf gain comparing index_reduce+torch.exp vs Default
=> Fuse sub+exp+sum and use index_reduce normalization in softmax by default

vllm_hpu_extension/ops.py
Pipelined PA implementation currently assumes GQA layout. 
This change fixes is so that any layout that is in attn scores is supported by adding additional dims to element-wise operations, that are applied to attn tensor so we operate on the same amount of dims.
This also fixes and issue of handing VLLM_PIPELINED_PA that was not parsed correctly.
=> Support non-GQA workloads in pipelined PA

calibration/calibrate_model.sh, calibration/step-2-measure-scales.py, calibration/step-3-postprocess_measure.py, calibration/step-4-quantize-scales.py
Cherry-pick of existing fix from main branch.
=> remove finish measurements and call shutdown (#50)

vllm_hpu_extension/ops.py
Tested with llama3.1-8b, see ~3% improvement
*** accuracy check ***
result using pipeline PA
```
Prompt: 'Hello, my name is', Generated text: ' Q-Tip\nNas > The Notorious B.I.G. - random'
Prompt: 'The president of the United States is', Generated text: ' someone who pushes the whole system to the very limits of what it can take.'
Prompt: 'The capital of France is', Generated text: ' also one of the most famous cities in the world, famous for its iconic landmarks'
Prompt: 'The future of AI is', Generated text: " here, and it's in the showers\nImagine stepping into a shower in a"
```
result using const pipeline PA
```
Processed prompts: 100%|███████████████████████████████████████████████| 4/4 [00:00<00:00,  6.31it/s, est. speed input: 41.02 toks/s, output: 100.96 toks/s]
Prompt: 'Hello, my …
```
=> Add const_pipeline_pa

vllm_hpu_extension/ops.py
=> Remove repeat KV cache

vllm_hpu_extension/ops.py
Modified to use fused_op as condition for FusedSDPA kernel.
vllm-for PR https://github.com/HabanaAI/vllm-fork/pull/725/files
=> Add change for interleave sliding window

vllm_hpu_extension/ops.py
Reverts HabanaAI/vllm-hpu-extension#84
=> Revert "Add change for interleave sliding window"

calibration/calibrate_model.sh, calibration/template/llama-2-chat.jinja, calibration/template/mistral_mixtral.jinja
- Moving Chat templates for Mixtral 8x7B and Llama2 as they were previously on separate, private repo.
- Currently, they are needed for model calibartion process, so we will keep as long as they are needed
- I validated the calibration process for Mixtral 8x7B and it works fine
=> Add Mixtral and Llama chat templates

calibration/README.md
=> Update multi-node calibration readme

calibration/calibrate_model.sh
Same as https://github.com/HabanaAI/vllm-hpu-extension/pull/93
=> Add different quant config for mixtral

vllm_hpu_extension/ops.py
Support initial enablement for text-embedding.
Need work with https://github.com/HabanaAI/vllm-fork/pull/758/files
=> Support the initial enablement for text-embedding

vllm_hpu_extension/ops.py
Current code doesn't work with fp8 (missmatched types with implementation of softmax, PatchedSoftmax)
=> Qwen fp8 support

vllm_hpu_extension/flags.py, vllm_hpu_extension/ops.py
Reverts HabanaAI/vllm-hpu-extension#60
PR to vllm-fork was reverted and due to api changes this has to be reverted too
=> Revert "vLLM-Ext: Full enabling of ALiBi"

vllm_hpu_extension/ops.py
The reshape of the query tensor has been moved to occur after applying the scale multiplication. This change allows for the fusion of the add bias operation (in models that use it) with the scale multiplication. In the current flow, this fusion is blocked due to the necessary reshape. The goal of this change is to eliminate the need for such a reshape, enabling the kernels to be fused.
Note: This PR assumes a different shape for the query tensor passed to flat_pa. A corresponding change in the vllm-fork is required for proper functionality.
=> Fuse add bias with scale mult

vllm_hpu_extension/utils.py
This reverts commit 4d3e5bfc2dc91e576770cde5b5c389c20f21ef1c.
=> Revert "Update utils.py (#122)"

vllm_hpu_extension/gptq_hpu.py
This PR is for fixing schema error on GPTQ models when using eager mode.
=> [FIX] Schema error on GPTQ

vllm_hpu_extension/utils.py
Adding proper "if" to attentnion kv cache update in case we have None values in keys and values (e.g. during decode in corss attention)
=> Handle cross-attn kv cache empty forward

vllm_hpu_extension/ops.py
Co-authored-by: Youlei Yang <youlei.yang@intel.com>
=> WA for fix sdpa kernel error

vllm_hpu_extension/flags.py, vllm_hpu_extension/ops.py
Coresponding PR: https://github.com/HabanaAI/vllm-fork/pull/942
=> merged_prefill+ - initial cleanup

vllm_hpu_extension/bucketing.py, vllm_hpu_extension/ops.py
Companion PR for https://github.com/HabanaAI/vllm-fork/pull/987
=> Experimental support for merged_prefill

vllm_hpu_extension/ops.py
Twin PR: [1020](https://github.com/HabanaAI/vllm-fork/pull/1020)
APC will use our existing implementation of prompt attention
=> APC - Remove prompt attn with context

calibration/step-3-postprocess_measure.py
This part work of https://github.com/HabanaAI/vllm-fork/pull/1030.
For the [MLA](https://github.com/HabanaAI/vllm-fork/blob/85f06932eeb7afd2c10d7333d2aeb76c830f6d85/vllm/attention/backends/hpu_attn.py#L171), where the key and value share a single tensor, we only keep one `VLLMKVCache`(`latent_cache_k`). 
In this case, we also want the second inputs of QK and AV to share the same calibration result with the `latent_cache_k`, so that we can eliminate the DQ-Q pair—just like in regular attention—to improve performance.
cc @hshen14 @thuang6
=> [SW-224465]Update post-process script for deepseek

vllm_hpu_extension/ops.py
Twin PR: [1059](https://github.com/HabanaAI/vllm-fork/pull/1059)
=> APC - Remove prompt attn with context and use existing implementation

vllm_hpu_extension/flags.py, vllm_hpu_extension/ops.py
@czhu15  I push two commits for dynamic moe setting both accuracy and performance, which has been tested on Gaudi2D, no functional  error.
=> [aice/v1.20.1] add dynamic moe setting for renormalize and performance tuning 

calibration/README.md, calibration/calibrate_model.sh, calibration/step-2-measure-scales.py, calibration/step-4-quantize-scales.py, calibration/step-5-unify_measurements.py
The feature has been orignaly introduced with #92 and experimentally deployed with release 1.20.0 #100.
Now we are introducing production ready multi-node support with vLLM including support for calibration.
=> Calibration with multi-node

calibration/README.md, calibration/calibrate_model.sh, calibration/step-2-measure-scales.py, calibration/step-4-quantize-scales.py, calibration/step-5-unify_measurements.py
Cherry-pick of PR #145 to v1.21.0 branch
=> [1.21.0 cherry-pick] Calibration with multi-node (#145)

vllm_hpu_extension/ops.py
Call dynamic MoE and static MoE in different situations.
=> Optimized MoE on Gaudi for aice/v1.20.1 branch

vllm_hpu_extension/ops.py
Temporarily reverts HabanaAI/vllm-hpu-extension#161
=> Revert "[DeepseekR1] porting 1.21 deepseek changes to main (#137)"

vllm_hpu_extension/ops.py
Reverts HabanaAI/vllm-hpu-extension#169
=> Reintroduce "[DeepseekR1] porting 1.21 deepseek changes to main (#137)"

vllm_hpu_extension/ops.py
Triangular attention seems unstable failing with graph compile issue.
=> Revert "[SW-225565] Enable triangular + attention bias"

vllm_hpu_extension/bucketing/exponential.py
Remove pdb trace from exponential bucketing
=> Remove pdb trace from exponential bucketing

vllm_hpu_extension/ops.py
https://jira.habana-labs.com/browse/SW-229036
Add necessary ops in vllm-hpu-extension to support fp8 models out of box
=> [SW-229036] out of box fp8 Dynamic scaling support

vllm_hpu_extension/ops.py
=> Enabled inc based FP8 moe for the branch aice/v1.20.1

vllm_hpu_extension/bucketing/exponential.py
Port from habana_main: Remove pdb trace from exponential bucketing
=> Port: Remove pdb trace from exponential bucketing

calibration/calibrate_model.sh, calibration/step-2-measure-scales.py, calibration/step-3-postprocess_measure.py, calibration/step-4-quantize-scales.py
Revert of 'Change quant config for deepseek (#160)' and Add support of deepseek fp8 calibration (#155)
=> Revert of 'Change quant config for deepseek (#160)' and Add support of deepseek fp8 calibration (#155)

vllm_hpu_extension/ops.py
=> Optimized MoE on Gaudi for the branch aice/v1.21.0

vllm_hpu_extension/bucketing/linear.py
Port from main: Fix decode blocks calculation for contiguous PA during warmup #198
=> Port: Fix decode blocks calculation for contiguous PA during warmup #198

vllm_hpu_extension/bucketing/common.py
Port: Set exponential bucketing as default
=> Port: Set exponential bucketing as default

vllm_hpu_extension/ops.py
=> Fix the variable name

calibration/calibrate_model.sh
cherrypick deepseek distill qwen2 calibration fix to aice/v1.21.0 branch.
=> [aice/1.21.0]Cherrypick qwen calibration fix

.github/dependabot.yml
It's necessary to enable Dependabot version updates
=> [SW-233275] Create dependabot.yml

vllm_hpu_extension/bucketing/exponential.py
vllm hpu-extension for automatization of long context, prompt
=> vllm hpu-extension for automatization of long context, prompt

vllm_hpu_extension/bucketing/exponential.py
Add exponential bucketing for warmup third dim
=> Add exponential bucketing for warmup third dim

vllm_hpu_extension/ops.py
Bug fix
add htcore.mark_step() afte fp32 softmax for fp8/INC too.
=> fix Qwen accuracy

vllm_hpu_extension/bucketing/exponential.py
Port: vllm hpu-extension for automatization of long context, prompt #249
=> Port: vllm hpu-extension for automatization of long context, prompt #249

calibration/calibrate_model.sh
Port: Use different quant config for Mixtral TC and lazy (#276)
=> Port: Use different quant config for Mixtral TC and lazy (#276)

calibration/calibrate_model.sh, calibration/step-2-measure-scales.py, calibration/step-4-quantize-scales.py
Port of PR https://github.com/HabanaAI/vllm-hpu-extension/pull/281 from main branch
=> Fix max-num-prefill-seqs issue on V1 (#281)

vllm_hpu_extension/profiler.py
Corresponding vllm-fork PR https://github.com/HabanaAI/vllm-fork/pull/1501
=> Add V0/V1 full profiling calculations to profiler utils

vllm_hpu_extension/ops.py, vllm_hpu_extension/utils.py
Pull in all window FusedSDPA support for Gemma3. 
- #299 
- #296 
- #285
=> Cherry-pick window FusedSDPA for Gemma3  onto v1.22

vllm_hpu_extension/gptq_hpu.py, vllm_hpu_extension/ops.py
Port of https://github.com/HabanaAI/vllm-hpu-extension/pull/306
=> [Security] Fix: remove dead code (#306)

vllm_hpu_extension/ops.py
Wrap the `chunk_size` check in a function, so that INC can retrieve the result by calling the same function.
@czhu15 @yangulei @ranzhejiang please help to review it. Thx!
cc @thuang6
=> Update MoE op

vllm_hpu_extension/config.py, vllm_hpu_extension/debug.py, vllm_hpu_extension/defragmentation.py, vllm_hpu_extension/environment.py, vllm_hpu_extension/features.py, vllm_hpu_extension/profiler.py, vllm_hpu_extension/runtime.py, vllm_hpu_extension/utils.py, vllm_hpu_extension/validation.py
fork PR: https://github.com/HabanaAI/vllm-fork/pull/1568
=> [V1] Defragmentation support

vllm_hpu_extension/ops.py
Cherry picked https://github.com/HabanaAI/vllm-hpu-extension/pull/316
=> Reintroduce fp16 requirement for fused softmax ops

calibration/calibrate_model.sh
model | FP32_SOFTMAX | Attention dtype
-- | -- | --
DeepSeek-R1-Distill-Llama-8B | FALSE | bfloat16
DeepSeek-R1-Distill-Qwen-7B | TRUE | bfloat16
DeepSeek-R1-Distill-Qwen-14B | FALSE | fp8
DeepSeek-R1-Distill-Qwen-32B | FALSE | fp8
DeepSeek-R1-Distill-Llama-70B | FALSE | fp8
Qwen3-8B | FALSE | bfloat16
Qwen3-14B | FALSE | bfloat16
Qwen3-32B | FALSE | fp8
Qwen3-30B-A3B | FALSE | fp8
Qwen3-235B-A22B | FALSE | bfloat16
QWQ 32B | FALSE | fp8
=> refine fp32_softmax and quant config

vllm_hpu_extension/ops.py
@czhu15 @Wei-Lin-Intel  @yangulei @yiliu30
=> [aice/v1.22.0] enable chunk moe

vllm_hpu_extension/ops.py
GLM-4.5-MOE model uses the compressed tensor path for FP8 inference. This PR optimizes the FP8 GEMMs and removes the blocks for FP8 MOE.
=> Add Support for GLM-4.5-MOE Compressed Tensor Path
